### ISSUE TITLE
Clover Build command

### ISSUE THREAD

**Issue by HelmoHass** [Micky1979/Clover-Configurator-Pro#1]
Hi,
not really an issue, but i was wondering if would be preferable since most already have use of it, to let the user choose the Build_Clover.command from the location where it is already, then eventually downloading it if not present. this will avoid creating a new directory for it and having less 'mess' around :)

**Comment by Micky1979** [comment]
Hi @HelmoHass, that directory is used for the backup as well. Yes I can decide a different location (thanks for the suggestion)... only one problem: the path must be writable by the current user.
Behind that there are some complications I have to think about and solve.

**Comment by Micky1979** [comment]
Beta 5 will have the possibility to download/use Build_Clover.command to and from a custom location!
![untitled](https://user-images.githubusercontent.com/20876032/34443694-20e45c40-ecc9-11e7-99a1-f1a1603ba364.png)
The directory chosen must be writable by the current user, or even if not writable (it's a condition) must contain Build_Clover.command: 
a directory can have restrictive write permissions and a user not able to delete/create file on it, but can also contain files with read/write permissions for the current user (taking the script with r/w permission it's up to you, and this only once). 

Anyway you'll be able to use and open Build_Clover.command from a custom location!
Thanks for the suggestion!

P.S. not yet published, will be soon

**Comment by Micky1979** [comment]
Done, Beta 5 is online, tell me if you like it

**Comment by HelmoHass** [comment]
Amazing,
i'll get it right away, Thanks.

**Comment by Micky1979** [comment]
You can update directly from the app ;-)

**Comment by Micky1979** [comment]
Ok, I'm closing this "issue". Post again if something goes wrong.
